[versions]
shadow_version = "8.1.1"
paperweight_version = "1.5.11"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight_version" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow_version" }

[libraries]
paperweight = { module = "io.papermc.paperweight:paperweight-patcher", version.ref = "paperweight_version" }
shadowjar = { module = "com.github.johnrengelman:shadow", version.ref = "shadow_version" }